# Generated by Django 5.0.6 on 2024-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=500)),
                ('short', models.CharField(max_length=300)),
                ('custom', models.CharField(max_length=250)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
